### ISSUE TITLE
Deadline exceeded on cluster upgrade to 1.16

### ISSUE THREAD

**Issue by autarchprinceps** [weaveworks/eksctl#2167]
**What happened?**
When doing a eksctl upgrade cluster I always run into a deadline waiting for the upgrade to succeed.
Error: waiting for requested "VersionUpdate" in cluster "prod" to succeed: RequestCanceled: waiter context canceled
caused by: context deadline exceeded

**What you expected to happen?**
The update in AWS goes through, but eksctl doesn't seem to wait long enough for that. Not sure what else would happen after that in eksctl, but this way, it won't be executed.

**How to reproduce it?**
For me it happens every time I upgrade a cluster. Haven't seen any conditions to this, other than that it happens with 1.16 (both rc.0 and rc.1 of 0.19 eksctl).

**Anything else we need to know?**
OS: Mac, IAM: assumed role, but session is definitively still valid.

**Versions**
❯ eksctl version
0.19.0-rc.1
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cPu1** [comment]
Thanks for the detailed issue. This was fixed in https://github.com/weaveworks/eksctl/pull/2151 but it did not make it to the RC. The fix will be out in `0.20.0`.

**Comment by cPu1** [comment]
Closing the issue for now, but feel free to reopen it if you're still having issues when the fix is out.

**Comment by ttrandba** [comment]
Still have the same issue with new version 0.20.0 
eksctl update cluster --name eksdev --approve
[ℹ]  eksctl version 0.20.0
[ℹ]  using region us-east-2
[ℹ]  will upgrade cluster "xxxx" control plane from current version "1.15" to "1.16"
Error: waiting for requested "VersionUpdate" in cluster "eksdev" to succeed: RequestCanceled: waiter context canceled
caused by: context deadline exceeded

**Comment by margoeth** [comment]
Before I made several cluster updates with eksctl 0.40.0 that took about 50 minutes and I never ran into that issue.
Now I made an update using eksctl 0.46.0 and I got that error after approximately 35 minutes.  The upgrade went through though and it seems to be "just" a problem with the observation of the process by eksctl.

Additional information:
- AWS region eu-central-1
- upgrades were all from kubernetes 1.15 to 1.16.

**Comment by bryan-munene** [comment]
I'm have this issue. As @margoeth said, the upgrade succeeds despite the error. These are the versions I'm running.
```
╰─ eksctl version
0.57.0
```
```
╰─ kubectl version --short   
Client Version: v1.21.1
Server Version: v1.20.7-eks-8be107
```
