### ISSUE TITLE
eksctl create cluster failing "coredns" is now schedulable onto Fargate

### ISSUE THREAD

**Issue by kristrt** [weaveworks/eksctl#2690]
Hello creating eks fargate cluster failing at the "coredns" is now schedulable onto Fargate.   It is blocking us and unable to meet our delivery timeline.   could you let us know what could be the cause.

2020-09-29T14:25:56-04:00 [ℹ]  created Fargate profile "fp-default" on EKS cluster "qa-cluster"
2020-09-29T14:25:56-04:00 [▶]  deployment "coredns" with compute type "ec2" currently has 0/2 replicas running
2020-09-29T14:25:56-04:00 [▶]  pod "coredns-75b44cb5b4-5ccj7" with compute type "ec2" and status "Pending" is scheduled on ""
2020-09-29T14:25:56-04:00 [ℹ]  "coredns" is now schedulable onto Fargate
2020-09-29T14:25:56-04:00 [▶]  deployment "coredns" with compute type "fargate" currently has 0/2 replicas running
2020-09-29T14:25:56-04:00 [▶]  pod "coredns-75b44cb5b4-5ccj7" with compute type "ec2" and status "Pending" is scheduled on ""
2020-09-29T14:25:57-04:00 [▶]  deployment "coredns" with compute type "fargate" currently has 0/2 replicas running
2020-09-29T14:25:57-04:00 [▶]  pod "coredns-5858fcd96-6t7ls" with compute type "fargate" and status "Pending" is scheduled on ""
2020-09-29T14:25:59-04:00 [▶]  deployment "coredns" with compute type "fargate" currently has 0/2 replicas running
2020-09-29T14:25:59-04:00 [▶]  pod "coredns-5858fcd96-6t7ls" with compute type "fargate" and status "Pending" is scheduled on ""
2020-09-29T14:26:03-04:00 [▶]  deployment "coredns" with compute type "fargate" currently has 0/2 replicas running
2020-09-29T14:26:03-04:00 [▶]  pod "coredns-5858fcd96-6t7ls" with compute type "fargate" and status "Pending" is scheduled on ""
2020-09-29T14:26:11-04:00 [▶]  deployment "coredns" with compute type "fargate" currently has 0/2 replicas running
2020-09-29T14:26:11-04:00 [▶]  pod "coredns-5858fcd96-6t7ls" with compute type "fargate" and status "Pending" is scheduled on ""
2020-09-29T14:26:27-04:00 [▶]  deployment "coredns" with compute type "fargate" currently has 0/2 replicas running
2020-09-29T14:26:27-04:00 [▶]  pod "coredns-5858fcd96-6t7ls" with compute type "fargate" and status "Pending" is scheduled on ""
2020-09-29T14:26:59-04:00 [▶]  deployment "coredns" with compute type "fargate" currently has 0/2 replicas running
2020-09-29T14:26:59-04:00 [▶]  pod "coredns-5858fcd96-6t7ls" with compute type "fargate" and status "Pending" is scheduled on ""
2020-09-29T14:28:03-04:00 [▶]  deployment "coredns" with compute type "fargate" currently has 0/2 replicas running
2020-09-29T14:28:03-04:00 [▶]  pod "coredns-5858fcd96-6t7ls" with compute type "fargate" and status "Pending" is scheduled on ""
2020-09-29T14:30:13-04:00 [▶]  deployment "coredns" with compute type "fargate" currently has 0/2 replicas running
2020-09-29T14:30:13-04:00 [▶]  pod "coredns-5858fcd96-6t7ls" with compute type "fargate" and status "Pending" is scheduled on ""
2020-09-29T14:34:29-04:00 [▶]  deployment "coredns" with compute type "fargate" currently has 0/2 replicas running
2020-09-29T14:34:29-04:00 [▶]  pod "coredns-5858fcd96-6t7ls" with compute type "fargate" and status "Pending" is scheduled on ""
2020-09-29T14:43:02-04:00 [▶]  failed task: create fargate profiles (will not run other sequential tasks)
2020-09-29T14:43:02-04:00 [▶]  failed task: create fargate profiles (will not run other sequential tasks)
2020-09-29T14:43:02-04:00 [▶]  failed task: create fargate profiles (will not run other sequential tasks)
2020-09-29T14:43:02-04:00 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2020-09-29T14:43:02-04:00 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-east-1 --name=qa-cluster'
2020-09-29T14:43:02-04:00 [✖]  Unauthorized

**Comment by michaelbeaumont** [comment]
Please include the config you're using.

**Comment by smitphilip** [comment]
hi... seeing the same. The command I'm using:

`eksctl create cluster --name cbp-data-service --version 1.17 --fargate --region <region> --profile <aws-config-profile> --tags project=proj529 --vpc-private-subnets=subnet-1,subnet-2`

Once the cluster is created, the default namespaces (and their fargate profiles) are created as expected:
```
> kubectl get namespace
NAME              STATUS   AGE
default           Active   28m
kube-node-lease   Active   28m
kube-public       Active   28m
kube-system       Active   28m
```
But kube-system pods are provisioned but never run... Any new pods as well; they result in the same... pods stuck in a pending state. 


```
> kubectl get events -n kube-system
LAST SEEN   TYPE      REASON              OBJECT                                  MESSAGE
14m         Warning   FailedScheduling    pod/coredns-rs-pod-ID1                  Pod provisioning timed out (will retry) for pod: kube-system/coredns-rs-pod-ID1
13m         Warning   FailedScheduling    pod/coredns-rs-pod-ID1                  Pod provisioning timed out (will retry) for pod: kube-system/coredns-rs-pod-ID1
11m         Warning   FailedScheduling    pod/coredns-rs-pod-ID1                  Pod provisioning timed out (will retry) for pod: kube-system/coredns-rs-pod-ID1
7m42s       Warning   FailedScheduling    pod/coredns-rs-pod-ID1                  Pod provisioning timed out (will retry) for pod: kube-system/coredns-rs-pod-ID1
14m         Warning   FailedScheduling    pod/coredns-rs-pod-ID                   Pod provisioning timed out (will retry) for pod: kube-system/coredns-rs-pod-ID
13m         Warning   FailedScheduling    pod/coredns-rs-pod-ID                   Pod provisioning timed out (will retry) for pod: kube-system/coredns-rs-pod-ID
11m         Warning   FailedScheduling    pod/coredns-rs-pod-ID                   Pod provisioning timed out (will retry) for pod: kube-system/coredns-rs-pod-ID
7m42s       Warning   FailedScheduling    pod/coredns-rs-pod-ID                   Pod provisioning timed out (will retry) for pod: kube-system/coredns-rs-pod-ID
17m         Normal    SuccessfulCreate    replicaset/coredns-rs-ID                Created pod: coredns-rs-pod-ID
17m         Normal    SuccessfulCreate    replicaset/coredns-rs-ID                Created pod: coredns-rs-pod-ID1
18m         Warning   FailedScheduling    pod/coredns-rs-pod-ID                   no nodes available to schedule pods
17m         Warning   FailedScheduling    pod/coredns-rs-pod-ID                   skip schedule deleting pod: kube-system/coredns-rs-pod-ID
2s          Warning   FailedScheduling    pod/coredns-rs-ID-ef2                   no nodes available to schedule pods
22m         Normal    SuccessfulCreate    replicaset/coredns-rs-ID                Created pod: coredns-rs-pod-ID
22m         Normal    SuccessfulCreate    replicaset/coredns-rs-ID                Created pod: coredns-rs-ID-ef2
17m         Normal    SuccessfulDelete    replicaset/coredns-rs-ID                Deleted pod: coredns-rs-pod-ID
22m         Normal    ScalingReplicaSet   deployment/coredns                      Scaled up replica set coredns-rs-ID to 2
17m         Normal    ScalingReplicaSet   deployment/coredns                      Scaled up replica set coredns-rs-ID to 1
17m         Normal    ScalingReplicaSet   deployment/coredns                      Scaled down replica set coredns-rs-ID to 1
17m         Normal    ScalingReplicaSet   deployment/coredns                      Scaled up replica set coredns-rs-ID to 2
21m         Normal    LeaderElection      configmap/cp-vpc-resource-controller    ip-1-2-3-4.regionName.compute.internal_NODEID became leader
22m         Normal    LeaderElection      configmap/eks-certificates-controller   ip-1-2-3-4.regionName.compute.internal became leader
18m         Normal    LeaderElection      configmap/fargate-scheduler             ip-1-2-3-4.regionName.compute.internal_UID3 became leader
22m         Normal    LeaderElection      endpoints/kube-controller-manager       ip-1-2-3-4.regionName.compute.internal_UID2 became leader
22m         Normal    LeaderElection      lease/kube-controller-manager           ip-1-2-3-4.regionName.compute.internal_UID2 became leader
22m         Normal    LeaderElection      endpoints/kube-scheduler                ip-1-2-3-4.regionName.compute.internal_UID1 became leader
22m         Normal    LeaderElection      lease/kube-scheduler                    ip-1-2-3-4.regionName.compute.internal_UID1 became leader
```

```
> kubectl get nodes -A
No resources found
```

**Comment by smitphilip** [comment]
I was able to solve the coredns scheduling issue with a:
```
kubectl rollout restart deployments -n kube-system
```
`kubectl get nodes` now return 3 nodes as well

or just delete the pods and replica-set will recreate them. Will have to do this during the creation of the cluster, cause it does look like there are other steps (i.e. ingress-controllers) that aren't executed due to the coredns issue.

Not sure why the above solves the issue, from debug logs it does look like eksctl tries to do the same

**Comment by PiotrBrzezianski** [comment]
I had a similar error reported when creating a cluster on fargate using a VPC that didn't have DNS hostnames enabled. 
The error was misleading because my pods were actually schedulled successfully (on fargate nodes), but the check is looking for pod's node name starting with "fargate-ip-" while without vpc dns hostnames the name is "fargate-<IP>" which fails the check.

**Comment by michaelbeaumont** [comment]
May have been fixed in https://github.com/weaveworks/eksctl/pull/2999

**Comment by marutiprasad** [comment]
This issue is still happening, incase of an all private cluster. 
Here is the cluster config yaml. 
`apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: app-service-dev
  region: us-west-2

vpc:
  id: "vpc-11111111"
  subnets:
    private:
      us-west-2a:
        id: "subnet-dfngkaejngjg11"
      us-west-2b:
        id: "subnet-dfngkaejngjg12"
      us-west-2c:
        id: "subnet-dfngkaejngjg13"
privateCluster:
  enabled: true
  
nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    privateNetworking: true

fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
  - name: fp-dev
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: service-dev`

**Comment by composer22** [comment]
This is still an issue w/ eksctl versions 0.36.2, 0.37.0. 

Config similar to OP's

- vpc id provided
- private subnets
- but ONLY using fargate.

Tested with EKS version 1.15 and 1.18
VPC has DNS hostnames and resolution enabled 
Nat gateways are assigned to private subnets and available

References:
https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html
https://github.com/weaveworks/eksctl/issues/1774

https://github.com/weaveworks/eksctl/pull/2999
NOTE: @michaelbeaumont michaelbeaumont merged commit 63c6b4f into weaveworks:master  on 4 Jan

error:

```
[ℹ]  "coredns" is now schedulable onto Fargate
[!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
[ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-west-2 --name=eks-test'
[✖]  failed to schedule core-dns on fargate: Unauthorized
Error: failed to create cluster "eks-test"
```

Validated coredns deployment 1.15:

Pod Template:
  Labels:           eks.amazonaws.com/component=coredns
                    k8s-app=kube-dns
  Annotations:      **eks.amazonaws.com/compute-type: fargate**



Suggested workaround above did not work alone.
```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-5f897d799c-4fvnb   0/1     Pending   0          58m
kube-system   coredns-8696bc9677-j8qn8   0/1     Pending   0          50m
kube-system   coredns-8696bc9677-n7gxn   0/1     Pending   0          50m

$ kubectl rollout restart deployments -n kube-system
deployment.extensions/coredns restarted
...
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-6fbb5c68d6-46gbq   0/1     Pending   0          3m33s
kube-system   coredns-6fbb5c68d6-5fcsc   0/1     Pending   0          3m33s
kube-system   coredns-8696bc9677-n7gxn   0/1     Pending   0          55m
```
You'll also notice the last one did not restart.

Removing the annotation (using above aws instructions) also didn't work with a restart. 
```
kubectl patch deployment coredns -n kube-system --type json \
-p='[{"op": "remove", "path": "/spec/template/metadata/annotations/eks.amazonaws.com~1compute-type"}]'
```
although all pods were restarted this time
```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-5d5cf4bd56-28v55   0/1     Pending   0          2m19s
kube-system   coredns-7b97956cbf-5q8jf   0/1     Pending   0          2m12s
kube-system   coredns-7b97956cbf-k6z6n   0/1     Pending   0          2m12s
```
likewise kubectl get events -n kube-system
results in similar error above
```
Pod provisioning timed out
```
```
$ kubectl get nodes -A
No resources found
```

Testing 1.18

Pod describe indicated

```
Annotations:          eks.amazonaws.com/compute-type: ec2
...
 Warning  FailedScheduling  39s (x24 over 33m)  default-scheduler  no nodes available to schedule pods
```

Yet deployment annotation is different

```
Annotations:      eks.amazonaws.com/compute-type: fargate
```

Applying roll pods picked up eks.amazonaws.com/compute-type: fargate
I had to delete the hung pod to force the scaling on one pod
```
 kubectl rollout restart deployments -n kube-system
```
still not starting
```
 Warning  FailedScheduling  <unknown>  fargate-scheduler  Pod provisioning timed out
```

**Comment by composer22** [comment]
problem solved. related to DNS config issue in vpc, not related to coredns

**Comment by aclevername** [comment]
> problem solved. related to DNS config issue in vpc, not related to coredns

i'm glad you managed to fix it @composer22. Could you expand upon exactly what was causing the problem and how you fixed it 😄 ? Thanks!

**Comment by ebr** [comment]
@composer22 I am also interested in knowing how you fixed it. would appreciate some insight

**Comment by aclevername** [comment]
Closing as I believe this is a duplicate of https://github.com/weaveworks/eksctl/issues/3155
