### ISSUE TITLE
panic: runtime error: invalid memory address with eksctl upgrade nodegroup 

### ISSUE THREAD

**Issue by jmolero-cortical** [weaveworks/eksctl#3102]
**What were you trying to accomplish?**

Trying to change the launch template version of a node group in a EKS cluster NOT created with eksctl

**What happened?**

As reported at #2174 and similar to #3092. When using the command:

`eksctl upgrade nodegroup --name=NG  --cluster=testcluster  --kubernetes-version 1.18  --launch-template-version 2`

The output is the following:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d8c2b3]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).upgradeAndWait(0xc0006379e0, 0x7ffeefbffb60, 0x13, 0x7ffeefbffba5, 0x4, 0x7ffeefbffbc4, 0x1, 0x0, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/actions/nodegroup/upgrade.go:60 +0x753
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).Upgrade(0xc0006379e0, 0x7ffeefbffb60, 0x13, 0x7ffeefbffba5, 0x4, 0x7ffeefbffbc4, 0x1, 0x0, 0xc0001ca8b0, 0xc000240d90)
	github.com/weaveworks/eksctl/pkg/actions/nodegroup/upgrade.go:38 +0x3e6
github.com/weaveworks/eksctl/pkg/ctl/upgrade.upgradeNodeGroup(0xc0006274a0, 0x7ffeefbffb60, 0x13, 0x7ffeefbffba5, 0x4, 0x7ffeefbffbc4, 0x1, 0x0, 0x1179565, 0xc0000d8400)
	github.com/weaveworks/eksctl/pkg/ctl/upgrade/nodegroup.go:86 +0x311
github.com/weaveworks/eksctl/pkg/ctl/upgrade.upgradeNodeGroupCmd.func1(0xc0000da000, 0xc00009cc60, 0x0, 0x6, 0x0, 0x0)
	github.com/weaveworks/eksctl/pkg/ctl/upgrade/nodegroup.go:27 +0xef
github.com/spf13/cobra.(*Command).execute(0xc0000da000, 0xc00009cc00, 0x6, 0x6, 0xc0000da000, 0xc00009cc00)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000844840, 0xc00064db10, 0x1, 0xc0008e9f70)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	github.com/weaveworks/eksctl/cmd/eksctl/main.go:76 +0x3ec
```

**How to reproduce it?**

Try to update the launch template version of a node group

**Logs**

**Anything else we need to know?**

Using the binary for MacOS

**Versions**

```
$ eksctl version
0.36.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aclevername** [comment]
Thanks for opening the issue @jmolero-cortical. Just to confirm, the nodegroup your trying to update was created with a launch template correct?

**Comment by aclevername** [comment]
Thanks for opening the issue @jmolero-cortical . 

I've attempted to recreate this by creating a `v1.17`  nodegroup in the EKS console, with a launch template and attempted to run the same update command as you. I did not get any failures
```
./eksctl upgrade nodegroup --name=ng-1 --cluster=jk --kubernetes-version 1.18 --launch-template-version 2
[ℹ]  upgrade of nodegroup "ng-1" in progress
[ℹ]  waiting for upgrade of nodegroup "ng-1" to complete
[ℹ]  waiting for upgrade of nodegroup "ng-1" to complete
[ℹ]  waiting for upgrade of nodegroup "ng-1" to complete
[ℹ]  waiting for upgrade of nodegroup "ng-1" to complete
[ℹ]  waiting for upgrade of nodegroup "ng-1" to complete
[ℹ]  waiting for upgrade of nodegroup "ng-1" to complete
[ℹ]  waiting for upgrade of nodegroup "ng-1" to complete
[ℹ]  waiting for upgrade of nodegroup "ng-1" to complete
[ℹ]  waiting for upgrade of nodegroup "ng-1" to complete
```
The panic you got implies that that nodegroup doesn't have a launch template ID attached. I just want to verify that the nodegroup your attempting to update was created with a launch template?

**Comment by jmolero-cortical** [comment]
Thanks for the quick support @aclevername . Sorry, I made a mistake, the NG had a launch template Id attached, but with the launch template I was trying to include user data and unfortunatelly in the user data I had a typo with the flag --enable-docker-bridge  (I was not including a true at the end).
Now, the behaviour is the same described at #3092
Thanks again for your time.

**Comment by aclevername** [comment]
> Thanks for the quick support @aclevername . Sorry, I made a mistake, the NG had a launch template Id attached, but with the launch template I was trying to include user data and unfortunatelly in the user data I had a typo with the flag --enable-docker-bridge (I was not including a true at the end).
> Now, the behaviour is the same described at #3092
> Thanks again for your time.

👍  makes sense. We will be releasing a fix for #3092 this week. In the meantime does the workaround mentioned in the issue unblock you?

**Comment by jmolero-cortical** [comment]
Yes, the workaround works

**Comment by aclevername** [comment]
Fixed in https://github.com/weaveworks/eksctl/releases/tag/0.36.1

**Comment by kieran-bacon-ngenius** [comment]
```
> eksctl get nodegroups --cluster ***
2021-10-01 19:39:42 [ℹ]  eksctl version 0.63.0
2021-10-01 19:39:42 [ℹ]  using region eu-west-2
2021-10-01 19:39:43 [!]  error collecting Cloudformation outputs for stack eksctl-nodegroup-model-inference-compute: no output "InstanceRoleARN" in stack "eksctl-nodegroup-model-inference-compute"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x21d48ae]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).getUnmanagedNodeGroupAutoScalingGroupName(0xc00056c0b0, 0xc000560700, 0xc00084ebc0, 0xc0004f6370, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/cfn/manager/nodegroup.go:262 +0xee
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).GetUnmanagedNodeGroupSummaries(0xc00056c0b0, 0x0, 0x0, 0x32d4760, 0xc00056c0b0, 0x9, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/cfn/manager/nodegroup.go:201 +0x234
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).GetAll(0xc00053bf80, 0xc000109d58, 0x3965e30, 0xc000545340, 0xc00053bf80, 0x0)
        github.com/weaveworks/eksctl/pkg/actions/nodegroup/get.go:19 +0x65
github.com/weaveworks/eksctl/pkg/ctl/get.doGetNodeGroup(0xc0008028f0, 0xc000398140, 0xc000108bd0, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/ctl/get/nodegroup.go:90 +0x327
github.com/weaveworks/eksctl/pkg/ctl/get.getNodeGroupCmd.func1(0xc000a2fb80, 0xc0004e8880, 0x0, 0x2, 0x0, 0x0)
        github.com/weaveworks/eksctl/pkg/ctl/get/nodegroup.go:32 +0xa5
github.com/spf13/cobra.(*Command).execute(0xc000a2fb80, 0xc0004e8860, 0x2, 0x2, 0xc000a2fb80, 0xc0004e8860)
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009b6280, 0xc000890aa0, 0x1, 0xc000bdff70)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        github.com/weaveworks/eksctl/cmd/eksctl/main.go:77 +0x41b
```

The problem still appears to be present, I have downloaded and installed the eksctl today.

**Comment by cPu1** [comment]
> ```
> > eksctl get nodegroups --cluster ***
> 2021-10-01 19:39:42 [ℹ]  eksctl version 0.63.0
> 2021-10-01 19:39:42 [ℹ]  using region eu-west-2
> 2021-10-01 19:39:43 [!]  error collecting Cloudformation outputs for stack eksctl-nodegroup-model-inference-compute: no output "InstanceRoleARN" in stack "eksctl-nodegroup-model-inference-compute"
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x0 pc=0x21d48ae]
> 
> goroutine 1 [running]:
> github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).getUnmanagedNodeGroupAutoScalingGroupName(0xc00056c0b0, 0xc000560700, 0xc00084ebc0, 0xc0004f6370, 0x0, 0x0)
>         github.com/weaveworks/eksctl/pkg/cfn/manager/nodegroup.go:262 +0xee
> github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).GetUnmanagedNodeGroupSummaries(0xc00056c0b0, 0x0, 0x0, 0x32d4760, 0xc00056c0b0, 0x9, 0x0, 0x0)
>         github.com/weaveworks/eksctl/pkg/cfn/manager/nodegroup.go:201 +0x234
> github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).GetAll(0xc00053bf80, 0xc000109d58, 0x3965e30, 0xc000545340, 0xc00053bf80, 0x0)
>         github.com/weaveworks/eksctl/pkg/actions/nodegroup/get.go:19 +0x65
> github.com/weaveworks/eksctl/pkg/ctl/get.doGetNodeGroup(0xc0008028f0, 0xc000398140, 0xc000108bd0, 0x0, 0x0)
>         github.com/weaveworks/eksctl/pkg/ctl/get/nodegroup.go:90 +0x327
> github.com/weaveworks/eksctl/pkg/ctl/get.getNodeGroupCmd.func1(0xc000a2fb80, 0xc0004e8880, 0x0, 0x2, 0x0, 0x0)
>         github.com/weaveworks/eksctl/pkg/ctl/get/nodegroup.go:32 +0xa5
> github.com/spf13/cobra.(*Command).execute(0xc000a2fb80, 0xc0004e8860, 0x2, 0x2, 0xc000a2fb80, 0xc0004e8860)
>         github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
> github.com/spf13/cobra.(*Command).ExecuteC(0xc0009b6280, 0xc000890aa0, 0x1, 0xc000bdff70)
>         github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
>         github.com/spf13/cobra@v1.2.1/command.go:902
> main.main()
>         github.com/weaveworks/eksctl/cmd/eksctl/main.go:77 +0x41b
> ```
> 
> The problem still appears to be present, I have downloaded and installed the eksctl today.

@kieran-bacon-ngenius you're still on 0.63 when the latest version is https://github.com/weaveworks/eksctl/releases/tag/v0.68.0. Can you try using the latest version and see if you're able to reproduce the issue?

**Comment by kieran-bacon-ngenius** [comment]
```
PS C:\Users\kieran> eksctl get nodegroups --cluster ***
2021-12-02 10:55:44 [ℹ]  eksctl version 0.75.0
2021-12-02 10:55:44 [ℹ]  using region eu-west-2
2021-12-02 10:55:44 [!]  error collecting Cloudformation outputs for stack eksctl-***-nodegroup-model-inference-compute: no output "InstanceRoleARN" in stack "eksctl-***-nodegroup-model-inference-compute"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x2936949]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).getUnmanagedNodeGroupAutoScalingGroupName(0xc000158160, 0xc0000c8c00)
        github.com/weaveworks/eksctl/pkg/cfn/manager/nodegroup.go:262 +0xc9
github.com/weaveworks/eksctl/pkg/cfn/manager.(*StackCollection).GetUnmanagedNodeGroupSummaries(0xc000b3fbe8, {0x0, 0x0})        github.com/weaveworks/eksctl/pkg/cfn/manager/nodegroup.go:201 +0x1e6
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).GetAll(0xc000149980)
        github.com/weaveworks/eksctl/pkg/actions/nodegroup/get.go:19 +0x48
github.com/weaveworks/eksctl/pkg/ctl/get.doGetNodeGroup(0xc0005473f0, 0xc0005cf720, 0xc000710a20)
        github.com/weaveworks/eksctl/pkg/ctl/get/nodegroup.go:76 +0x15b
github.com/weaveworks/eksctl/pkg/ctl/get.getNodeGroupCmd.func1(0xc0001cb180, {0xc0003059e0, 0x2, 0x2})
        github.com/weaveworks/eksctl/pkg/ctl/get/nodegroup.go:32 +0x78
github.com/spf13/cobra.(*Command).execute(0xc0001cb180, {0xc0003059c0, 0x2, 0x2})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00072e780)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        github.com/weaveworks/eksctl/cmd/eksctl/main.go:99 +0x525
```

@cPu1 good catch, unfortunately, it still appears to be a problem and I've upgraded the package today.

**Comment by jgalliers** [comment]
Hi all, 

I received this error today after a fresh install of v0.104.0

```
j@jvm$ eksctl version
0.104.0-dev+6f5ce912.2022-06-24T12:46:32Z
j@jvm:$ eksctl upgrade nodegroup --name=hardening-test --cluster=dev --launch-template-version 5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3a771ab]

goroutine 1 [running]:
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).upgradeUsingAPI(0xc000119860, {0x53d6c28, 0xc0000720d0}, {{0x7fffc078d1b1, 0xe}, {0x0, 0x0}, {0x7fffc078d1e8, 0x1}, 0x0, ...}, ...)
	/tmp/eksctl-20220624-3451-qe9yyf/pkg/actions/nodegroup/upgrade.go:115 +0x2cb
github.com/weaveworks/eksctl/pkg/actions/nodegroup.(*Manager).Upgrade(0xc000119860, {0x53d6c28, 0xc0000720d0}, {{0x7fffc078d1b1, 0xe}, {0x0, 0x0}, {0x7fffc078d1e8, 0x1}, 0x0, ...})
	/tmp/eksctl-20220624-3451-qe9yyf/pkg/actions/nodegroup/upgrade.go:84 +0x333
github.com/weaveworks/eksctl/pkg/ctl/upgrade.upgradeNodeGroup(0xc000cefc98?, {{0x7fffc078d1b1, 0xe}, {0x0, 0x0}, {0x7fffc078d1e8, 0x1}, 0x0, {0x0, 0x0}, ...})
	/tmp/eksctl-20220624-3451-qe9yyf/pkg/ctl/upgrade/nodegroup.go:84 +0x347
github.com/weaveworks/eksctl/pkg/ctl/upgrade.upgradeNodeGroupCmd.func1(0xc000341900?, {0xc000c1ab00?, 0x4?, 0x4?})
	/tmp/eksctl-20220624-3451-qe9yyf/pkg/ctl/upgrade/nodegroup.go:28 +0x9b
github.com/spf13/cobra.(*Command).execute(0xc000341900, {0xc000c1aac0, 0x4, 0x4})
	/github/home/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00066d900)
	/github/home/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/github/home/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/tmp/eksctl-20220624-3451-qe9yyf/cmd/eksctl/main.go:102 +0x5db
```


Is there something I'm missing?

**Comment by cPu1** [comment]
@jgalliers, thanks for the detailed report. I don't think you can update the launch template via `update-nodegroup-version` if the nodegroup is in a degraded state. Your best bet is to recreate the nodegroup with the new launch template. 

But your testing did surface a panic in `eksctl upgrade nodegroup`. We'll work on this soon.
