### ISSUE TITLE
MFA errors when checking dependencies

### ISSUE THREAD

**Issue by richardcase** [weaveworks/eksctl#71]
If you are using MFA there are 2 errors reported from `CheckAllCommands`. Specifically when getting the kubectl version and then when checking the server version:
```bash
2018-06-19T17:20:17+01:00 [▶]  kubectl: "/usr/local/bin/kubectl"
2018-06-19T17:20:17+01:00 [▶]  clientVersion="v1.10.2" err="Assume Role MFA token code: could not get token: EOF\nUnable to connect to the server: getting token: exec: exit status 1\n"
2018-06-19T17:20:17+01:00 [▶]  heptio-authenticator-aws: "/Users/richardcase/bin/heptio-authenticator-aws"
2018-06-19T17:20:17+01:00 [✖]  unable to use kubectl with the EKS cluster (check ' --kubeconfig /Users/richardcase/.kube/config version'): Assume Role MFA token code: could not get token: EOF
Unable to connect to the server: getting token: exec: exit status 1
2018-06-19T17:20:17+01:00 [ℹ]  cluster should be functions despite missing client binaries that need to be installed in the PATH
```

Potentially the following should happen:
- Only get the client version in `CheckKubectlVersion`. This would be by setting `--client=true`
- Not checking the server version in `CheckAllCommands`. As it stands eksctl doesn't allow you to specify a Kubernetes version (i.e. it gets the latest version supported by EKS). Should we expose a version flag then we can check its above the minimum version supported.

**Comment by richardcase** [comment]
I think its any profile that uses MFA will get this issue. But if environment variables are used for static credentials then it will be fine.

**Comment by errordeveloper** [comment]
@richardcase I think this should be resolved now, if so – please close.

**Comment by richardcase** [comment]
I just checked and its still an issue:
```bash
2018-07-06T18:32:21+01:00 [✖]  unable to use kubectl with the EKS cluster (check 'kubectl --kubeconfig=/Users/bob/.kube/eksctl/clusters/bobtest5 version'): Assume Role MFA token code: could not get token: EOF
Unable to connect to the server: getting credentials: exec: exit status 1
```

I'm investigating now.

**Comment by errordeveloper** [comment]
@richardcase how far did you get in your investigation? Could you describe how this error can be reproduced?

**Comment by richardcase** [comment]
The problem is caused when we have a profile that use MFA. 

Looking into this the error's coming from within `CheckAllCommands` and the call to [get the kubectl version](https://github.com/weaveworks/eksctl/blob/master/pkg/utils/kubectl.go#L66).

Looking further this is a issue with the `weaveworks/launcher` vendored package and specifically the the [ExecuteOutputMatrix](https://github.com/weaveworks/eksctl/blob/master/vendor/github.com/weaveworks/launcher/pkg/kubectl/local.go#L41). 

As we are not setting stdin on the command it defaults to the null device and so there is no way to handle the prompt for the MFA token in the sub-process.

This is part of the comment from [here](https://golang.org/pkg/os/exec/):
```go
// If Stdin is nil, the process reads from the null device (os.DevNull).
```

**Comment by richardcase** [comment]
And i'm running this command when i see the issue:
```bash
AWS_PROFILE=dev ./eksctl create cluster -n richtest8 -N 1 --auto-kubeconfig
```

**Comment by errordeveloper** [comment]
While testing this, I am starting to see a DNS lookup error (which is weird, because by the time we get here we've already used the API for other operations).

```
2018-07-09T11:40:59+01:00 [ℹ]  the cluster has 1 nodes
2018-07-09T11:40:59+01:00 [ℹ]  node "ip-192-168-250-108.us-west-2.compute.internal" is ready
2018-07-09T11:40:59+01:00 [▶]  kubectl: "/Users/ilya/Library/Local/Homebrew/bin/kubectl"
2018-07-09T11:40:59+01:00 [▶]  clientVersion="v1.11.0" err="Unable to connect to the server: dial tcp: lookup 3CC12A70C4C072F7357BF9B6100497FA.sk1.us-west-2.eks.amazonaws.com: no such host\n"
2018-07-09T11:40:59+01:00 [▶]  heptio-authenticator-aws: "/Users/ilya/Library/Local/Homebrew/bin/heptio-authenticator-aws"
2018-07-09T11:41:00+01:00 [ℹ]  kubectl command should work with "/Users/ilya/.kube/eksctl/clusters/test-1", try 'kubectl --kubeconfig=/Users/ilya/.kube/eksctl/clusters/test-1 get nodes'
```

**Comment by errordeveloper** [comment]
As discussed, we should be able to fix this by passing effective credentials as environment variables to `kubectl` (and in tuns the authenticator). I'll make a PR to incorporate this based on weaveworks/launcher#237 shortly.
